name: Components Update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight UTC

jobs:
  update-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Update components
        run: |
          npx -y shadcn-svelte@latest update -ay
          npx -y jsrepo update --all --yes --overwrite
          npx -y prettier -cw .
          git restore package.json

      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore: updated components"
          branch: "chore/update-components-${{ github.run_id }}"
          title: "chore: update components"
          body: "This PR updates the components to the latest versions."
          base: main
          sign-commits: true
          labels: components-update
